import type { EventEntry, Patient, PatientId, WorkItem } from './types'

export const PATIENTS: Record<PatientId, Patient> = {
  'P-001': {
    id: 'P-001',
    bed: 'Bed 4',
    age: 41,
    admissionNote: 'Day 2 after open appendicectomy',
    allergies: [],
    currentState: [
      'Comfortable overnight',
      'Last pain score 3/10',
      'Wound dry',
      'Eating and drinking',
      'Cannula — left hand',
      'Observations 6-hourly · last taken 06:00',
    ],
  },
  'P-002': {
    id: 'P-002',
    bed: 'Bed 9',
    age: 63,
    admissionNote: 'Day 1 after bowel resection',
    allergies: [],
    currentState: [
      'Restless',
      'Pain 7/10 at 05:00',
      'Morphine given 05:15',
      'Temperature 37.9°C at 06:00',
      'NPO',
      'IV fluids running — 1L / 8h',
      'Catheter draining',
    ],
  },
  'P-003': {
    id: 'P-003',
    bed: 'Bed 12',
    age: 28,
    admissionNote: 'Admitted overnight with abdominal pain',
    allergies: ['Penicillin'],
    currentState: [
      'NPO since midnight',
      'Anxious',
      'Asking when she will be seen',
      'Consent not signed',
      'Bloods taken 04:00 — results pending',
      'Possible theatre later if surgeon agrees',
    ],
  },
}

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  {
    id: 'p002-wound-review',
    patientId: 'P-002',
    title: 'Pain / wound review',
    category: 'Clinical review',
    state: 'WAITING',
    owner: 'Doctor',
    waitingFor: 'Doctor',
    since: '05:30',
    note: 'Requested by night nurse',
    overdue: true,
    showInNow: true,
  },
  {
    id: 'p002-iv-fluids-review',
    patientId: 'P-002',
    title: 'IV fluids review',
    category: 'Medication / fluids',
    state: 'NEXT',
    owner: 'Me',
    note: 'Ongoing',
    overdue: false,
    showInNow: false,
  },
  {
    id: 'p003-blood-results',
    patientId: 'P-003',
    title: 'Blood results',
    category: 'Investigation',
    state: 'WAITING',
    owner: 'Lab',
    waitingFor: 'Lab result',
    since: '04:00',
    note: 'Taken 04:00 · pending',
    overdue: false,
    showInNow: true,
  },
  {
    id: 'p003-theatre-decision',
    patientId: 'P-003',
    title: 'Theatre decision',
    category: 'Plan',
    state: 'OPEN',
    owner: 'Surgeon',
    waitingFor: 'Surgeon',
    note: 'Pending surgeon review',
    overdue: false,
    showInNow: false,
  },
  {
    id: 'p003-consent',
    patientId: 'P-003',
    title: 'Consent',
    category: 'Admin',
    state: 'OPEN',
    owner: 'Me',
    note: 'Not yet signed',
    overdue: false,
    showInNow: false,
  },
  {
    id: 'p001-observations',
    patientId: 'P-001',
    title: 'Morning observations',
    category: 'Observations',
    state: 'NEXT',
    owner: 'Me',
    due: '12:00',
    overdue: false,
    showInNow: false,
  },
  {
    id: 'p001-mobilisation',
    patientId: 'P-001',
    title: 'Mobilisation',
    category: 'Physiotherapy',
    state: 'NEXT',
    owner: 'Me',
    due: 'Today',
    note: 'Physiotherapy asked her to walk this morning',
    overdue: false,
    showInNow: false,
  },
]

export const INITIAL_EVENTS: EventEntry[] = [
  { id: 'e1', patientId: 'P-002', time: '07:00', label: 'Morning shift started' },
  { id: 'e2', patientId: 'P-001', time: '06:00', label: 'Observations recorded' },
  { id: 'e3', patientId: 'P-002', time: '06:00', label: 'Temperature 37.9°C' },
  { id: 'e4', patientId: 'P-002', time: '05:15', label: 'Morphine administered' },
  { id: 'e5', patientId: 'P-002', time: '05:00', label: 'Pain 7/10' },
  { id: 'e6', patientId: 'P-003', time: '04:00', label: 'Bloods taken' },
]

export const INITIAL_HANDOVER_NOTES: Record<PatientId, string[]> = {
  'P-001': ['Mobilisation requested — physiotherapy asked her to walk this morning'],
  'P-002': ['Doctor wound review still unresolved', 'Pain management follow-up'],
  'P-003': ['Blood result pending', 'Theatre decision pending', 'Consent not signed'],
}
