import type { DemoData } from './types'

export function createInitialData(): DemoData {
  return {
    nurseName: 'Edith',
    ward: 'Medical Ward',
    shiftLabel: 'Morning shift',
    nowMinutes: 655,
    teams: [
      { id: 'team-medical', name: 'Medical Ward', kind: 'ward' },
      { id: 'team-pharmacy', name: 'Pharmacy', kind: 'pharmacy' },
      { id: 'team-lab', name: 'Laboratory', kind: 'laboratory' },
      { id: 'team-ed', name: 'Emergency Unit', kind: 'emergency' },
    ],
    owners: [
      { id: 'edith', name: 'Edith', role: 'Staff Nurse', teamId: 'team-medical', persona: 'edith' },
      { id: 'ama', name: 'Ama', role: 'Nurse In-Charge', teamId: 'team-medical', persona: 'ama' },
      { id: 'kwame', name: 'Kwame', role: 'Pharmacist', teamId: 'team-pharmacy' },
      { id: 'efua', name: 'Efua', role: 'Laboratory Scientist', teamId: 'team-lab' },
      { id: 'dr-mensah', name: 'Dr Mensah', role: 'Doctor', teamId: 'team-medical' },
    ],
    beds: [
      { id: 'bed08', label: 'Bed 08', status: 'Stable', nextReview: '12:00 PM' },
      { id: 'bed11', label: 'Bed 11', status: 'Awaiting review', nextReview: '11:30 AM' },
      { id: 'bed14', label: 'Bed 14', status: 'Discharge planning', nextReview: '1:00 PM' },
    ],
    careContexts: [
      { id: 'bed08', label: 'Bed 08', kind: 'bed', status: 'Stable' },
      { id: 'bed11', label: 'Bed 11', kind: 'bed', status: 'Awaiting review' },
      { id: 'bed14', label: 'Bed 14', kind: 'bed', status: 'Discharge planning' },
      { id: 'ed-admit-2', label: 'ED Admission 2', kind: 'emergency', status: 'Accepted to Medical Ward' },
    ],
    work: [
      {
        id: 'w-med-review',
        bedId: 'bed11',
        contextId: 'bed11',
        scope: 'team',
        owningTeamId: 'team-medical',
        sourceTeamId: 'team-medical',
        receivingTeamId: 'team-pharmacy',
        ownerId: 'edith',
        title: 'Medication review before next dose',
        description: 'Medication chart copied from the existing record. Pharmacy review is needed before the nurse continues.',
        status: 'IN_PROGRESS',
        priority: 'now',
        dueLabel: 'Due 11:30 AM',
        dueAtMinutes: 690,
        assignedTo: 'Edith',
        startedAt: '10:15 AM',
        completedAt: null,
        waitingOn: 'Pharmacy review',
        waitingSinceLabel: 'Waiting 25 min',
        sourceType: 'capture',
        sourceSummary: 'Copied from existing medication chart; EHR remains the official record.',
        handoverNote: 'If Pharmacy has not responded before handover, incoming nurse should chase Pharmacy and confirm the next action.',
        syncState: 'SYNCED',
      },
      {
        id: 'w-lab-response',
        bedId: 'bed08',
        contextId: 'bed08',
        scope: 'team',
        owningTeamId: 'team-medical',
        sourceTeamId: 'team-medical',
        receivingTeamId: 'team-lab',
        ownerId: 'edith',
        title: 'Review lab response and continue fluids plan',
        description: 'Laboratory response has arrived. Nurse needs to continue the operational follow-up with the responsible doctor.',
        status: 'IN_PROGRESS',
        priority: 'now',
        dueLabel: 'Response received',
        dueAtMinutes: 650,
        assignedTo: 'Edith',
        startedAt: '10:05 AM',
        completedAt: null,
        sourceType: 'capture',
        sourceSummary: 'Lab response updated the work item; no clinical interpretation is made by Enore.',
        handoverNote: 'Confirm plan with Dr Mensah if not completed before shift handover.',
        syncState: 'SYNCED',
      },
      {
        id: 'w-personal-note',
        bedId: null,
        contextId: undefined,
        scope: 'personal',
        ownerId: 'edith',
        title: 'Follow up discharge paperwork note',
        description: 'Personal note captured during ward round. It can be connected to the team when Edith is ready.',
        status: 'TO_DO',
        priority: 'soon',
        dueLabel: 'Before handover',
        dueAtMinutes: 780,
        assignedTo: 'Edith',
        startedAt: null,
        completedAt: null,
        sourceType: 'paper',
        sourceSummary: 'Personal Paper Capture: "Bed 14 discharge paperwork - check forms before handover."',
        handoverNote: 'Not yet visible to the team until connected.',
        syncState: 'LOCAL',
      },
      {
        id: 'w-ed-admission',
        bedId: null,
        contextId: 'ed-admit-2',
        scope: 'team',
        owningTeamId: 'team-medical',
        sourceTeamId: 'team-ed',
        receivingTeamId: 'team-medical',
        ownerId: 'ama',
        title: 'Prepare ward bed for ED admission',
        description: 'Emergency Unit has requested a Medical Ward admission. Ward team owns the next operational step.',
        status: 'TO_DO',
        priority: 'soon',
        dueLabel: 'Due 11:45 AM',
        dueAtMinutes: 705,
        assignedTo: 'Ama',
        startedAt: null,
        completedAt: null,
        sourceType: 'external',
        sourceSummary: 'ED handoff copied into Enore as work; ED is not an internal chat thread.',
        handoverNote: 'If admission is delayed, keep visible for incoming nurse in-charge.',
        syncState: 'SYNCED',
      },
      {
        id: 'w-external-call',
        bedId: 'bed14',
        contextId: 'bed14',
        scope: 'team',
        owningTeamId: 'team-medical',
        ownerId: 'ama',
        title: 'Return referring clinic call about discharge paperwork',
        description: 'External communication created work for the responsible team. The clinic is not a workspace member.',
        status: 'TO_DO',
        priority: 'soon',
        dueLabel: 'Today',
        dueAtMinutes: 760,
        assignedTo: 'Ama',
        startedAt: null,
        completedAt: null,
        followUpNeeded: true,
        sourceType: 'external',
        sourceSummary: 'Phone call from referring clinic; outcome should be recorded after professional review.',
        handoverNote: 'Record whether the clinic was called back before handover.',
        syncState: 'SYNCED',
      },
    ],
    dependencies: [
      {
        id: 'dep-pharmacy-review',
        workId: 'w-med-review',
        requestedByTeamId: 'team-medical',
        requestedFromTeamId: 'team-pharmacy',
        requestedFromRole: 'Pharmacist',
        ownerId: 'kwame',
        status: 'WAITING',
        waitingOn: 'Pharmacy review',
        requestedAtLabel: '10:20 AM',
        expectedAtLabel: '11:00 AM',
        expectedAtMinutes: 660,
        nextAction: 'Continue medication workflow after Pharmacy responds.',
      },
      {
        id: 'dep-lab-response',
        workId: 'w-lab-response',
        requestedByTeamId: 'team-medical',
        requestedFromTeamId: 'team-lab',
        requestedFromRole: 'Laboratory Scientist',
        ownerId: 'efua',
        status: 'RESPONDED',
        waitingOn: 'Laboratory response',
        requestedAtLabel: '9:50 AM',
        expectedAtLabel: '10:30 AM',
        expectedAtMinutes: 630,
        responseSummary: 'Result available. Nurse to continue operational follow-up with Dr Mensah.',
        respondedAtLabel: '10:48 AM',
        nextAction: 'Edith reviews the response and continues the work.',
      },
    ],
    followUps: [
      {
        id: 'fu-external-call',
        workId: 'w-external-call',
        ownerId: 'ama',
        dueLabel: 'Before 1:00 PM',
        dueAtMinutes: 780,
        status: 'DUE',
        note: 'Call the referring clinic back after professional review.',
      },
    ],
    externalContacts: [
      {
        id: 'clinic-north',
        displayLabel: 'Northside Clinic',
        type: 'referrer',
        relationshipLabel: 'Referring facility',
        channelHint: 'phone',
      },
    ],
    externalCommunications: [
      {
        id: 'ext-1',
        contactId: 'clinic-north',
        workId: 'w-external-call',
        careContextId: 'bed14',
        channel: 'phone',
        direction: 'inbound',
        summary: 'Clinic called to ask whether discharge paperwork can be returned today.',
        receivedAtLabel: '10:30 AM',
        reviewedById: 'ama',
        outcome: 'Work created for ward team review. No external workspace access granted.',
      },
    ],
    changes: [
      {
        id: 'c1',
        workId: 'w-med-review',
        type: 'dependencyRequested',
        text: 'Medical Ward requested Pharmacy review for medication work.',
        timeLabel: '10:20 AM',
        syncState: 'SYNCED',
      },
      {
        id: 'c2',
        workId: 'w-lab-response',
        type: 'dependencyResponded',
        text: 'Laboratory response received; nurse continuation needed.',
        timeLabel: '10:48 AM',
        syncState: 'SYNCED',
      },
      {
        id: 'c3',
        workId: 'w-personal-note',
        type: 'created',
        text: 'Personal paper note saved locally by Edith.',
        timeLabel: '10:50 AM',
        syncState: 'LOCAL',
      },
    ],
    teamActivity: [
      { bedId: 'bed08', text: 'Laboratory response received. Edith needs to continue the workflow.' },
      { bedId: 'bed11', text: 'Medication review is waiting on Pharmacy.' },
      { bedId: 'bed14', text: 'External clinic call created ward follow-up work.' },
      { bedId: 'ed-admit-2', text: 'Emergency Unit admission request is visible to the Medical Ward.' },
    ],
    recentUpdate: { workId: 'w-lab-response', bedId: 'bed08', timeLabel: '10:48 AM' },
    meeting: {
      id: 'm1',
      title: 'Ward Meeting',
      dateLabel: 'Today - 8:00 AM',
      discussion: 'Documentation delays discussed.',
      decision: 'Review documentation workflow.',
      actionTitle: 'Follow up with ward administration on documentation workflow',
      actionOwner: 'Nurse In-Charge',
      followUp: 'Next ward meeting.',
      actionAdded: false,
    },
  }
}
