import type { DemoData } from './types'

export function createInitialData(): DemoData {
  return {
    nurseName: 'Edith',
    ward: 'Medical Ward',
    shiftLabel: 'Morning shift',
    beds: [
      { id: 'bed08', label: 'Bed 08', status: 'Stable', nextReview: '12:00 PM' },
      { id: 'bed11', label: 'Bed 11', status: 'Stable', nextReview: '11:20 AM' },
      { id: 'bed14', label: 'Bed 14', status: 'Stable', nextReview: '1:00 PM' },
    ],
    careContexts: [
      { id: 'bed08', label: 'Bed 08', kind: 'bed', status: 'Stable' },
      { id: 'bed11', label: 'Bed 11', kind: 'bed', status: 'Stable' },
      { id: 'bed14', label: 'Bed 14', kind: 'bed', status: 'Stable' },
      { id: 'theatre-1', label: 'Theatre — Case 3', kind: 'theatre', status: 'In progress · 09:30' },
    ],
    work: [
      // Edith's scripted Personal Workspace items — unchanged from the original build.
      {
        id: 'w1',
        bedId: 'bed08',
        title: 'Wound dressing',
        status: 'TO_DO',
        dueLabel: 'Due now',
        assignedTo: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: 'w2',
        bedId: 'bed11',
        title: 'Fluid balance review',
        status: 'IN_PROGRESS',
        dueLabel: 'Due in 20 min',
        assignedTo: 'Edith',
        startedAt: '10:05 AM',
        completedAt: null,
      },
      {
        id: 'w3',
        bedId: 'bed14',
        title: 'Medication follow-up',
        status: 'TO_DO',
        dueLabel: 'Due in 45 min',
        assignedTo: 'Kwame',
        startedAt: null,
        completedAt: null,
      },
      // Team Workspace demo work — shared ward and non-ward-bed items, appended after Edith's
      // scripted items so her Personal Workspace ordering/behaviour is unaffected.
      {
        id: 'w4',
        bedId: null,
        title: 'Medication trolley restocking',
        status: 'TO_DO',
        dueLabel: 'Unassigned',
        assignedTo: null,
        startedAt: null,
        completedAt: null,
      },
      {
        id: 'w5',
        bedId: null,
        title: 'Patient transfer coordination',
        status: 'IN_PROGRESS',
        dueLabel: 'In progress',
        assignedTo: 'Ama',
        startedAt: '9:50 AM',
        completedAt: null,
        waitingOn: 'Receiving team response',
        waitingSinceLabel: 'Waiting 12 min',
      },
      {
        id: 'w6',
        bedId: 'bed11',
        title: 'Medication review',
        status: 'IN_PROGRESS',
        dueLabel: 'In progress',
        assignedTo: 'Ama',
        startedAt: '9:35 AM',
        completedAt: null,
        waitingOn: 'Awaiting pharmacy response',
        waitingSinceLabel: 'Waiting 35 min',
      },
      {
        id: 'w7',
        bedId: 'bed14',
        title: 'Clinical review requested',
        status: 'ESCALATED',
        dueLabel: 'Escalated',
        assignedTo: null,
        startedAt: null,
        completedAt: null,
        escalationReason: 'Deteriorating observations',
        escalatedAtLabel: 'Escalated 18 min ago',
      },
      {
        id: 'w8',
        bedId: 'bed08',
        title: 'Relative requested an update',
        status: 'TO_DO',
        dueLabel: 'Follow-up needed',
        assignedTo: null,
        startedAt: null,
        completedAt: null,
        followUpNeeded: true,
      },
      {
        id: 'w9',
        bedId: null,
        contextId: 'theatre-1',
        title: 'Consent form outstanding',
        status: 'TO_DO',
        dueLabel: 'Before 09:00',
        assignedTo: null,
        startedAt: null,
        completedAt: null,
      },
    ],
    changes: [
      { id: 'c1', text: 'Fluid balance review started for Bed 11', timeLabel: '8:40 AM' },
      { id: 'c2', text: 'Medication follow-up flagged for Bed 14', timeLabel: '9:15 AM' },
    ],
    teamActivity: [
      { bedId: 'bed08', text: 'No one has started this yet.' },
      { bedId: 'bed11', text: 'Ama is reviewing intake and output charts.' },
      { bedId: 'bed14', text: 'Team notified. Awaiting response from pharmacy.' },
      { bedId: 'theatre-1', text: 'Theatre list confirmed for 09:30.' },
    ],
    recentUpdate: null,
    meeting: {
      id: 'm1',
      title: 'Ward Meeting',
      dateLabel: 'Today · 8:00 AM',
      discussion: 'Documentation delays discussed.',
      decision: 'Review documentation workflow.',
      actionTitle: 'Follow up with ward administration on documentation workflow',
      actionOwner: 'Nurse In-Charge',
      followUp: 'Next ward meeting.',
      actionAdded: false,
    },
  }
}
